// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroLegal.Infraestructura.Persistance.Context;

#nullable disable

namespace RegistroLegal.Infraestructura.Persistance.Migrations
{
    [DbContext(typeof(AppRegistroLegalContext))]
    [Migration("20250831001314_updateMaxLengthPersona")]
    partial class updateMaxLengthPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Carpeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carpetas");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Ilicito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime>("FechaAcusacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MedioId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MedioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Ilicito", (string)null);
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.InfraccionCarpeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarpetaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<int>("InfraccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("InfraccionId");

                    b.ToTable("InfraccionCarpetas");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Medio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMedio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Medios");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Ilicito", b =>
                {
                    b.HasOne("RegistroLegal.Core.Domain.Entity.Medio", "Medio")
                        .WithMany("Cargos")
                        .HasForeignKey("MedioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegistroLegal.Core.Domain.Entity.Persona", "Persona")
                        .WithMany("Cargos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medio");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.InfraccionCarpeta", b =>
                {
                    b.HasOne("RegistroLegal.Core.Domain.Entity.Carpeta", "Carpeta")
                        .WithMany("CarpetaInfracciones")
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroLegal.Core.Domain.Entity.Ilicito", "Infraccion")
                        .WithMany("CarpetaInfracciones")
                        .HasForeignKey("InfraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carpeta");

                    b.Navigation("Infraccion");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Carpeta", b =>
                {
                    b.Navigation("CarpetaInfracciones");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Ilicito", b =>
                {
                    b.Navigation("CarpetaInfracciones");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Medio", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("RegistroLegal.Core.Domain.Entity.Persona", b =>
                {
                    b.Navigation("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
